#**INTRODUCCIÓN A PYTHON**



##Generalidades


In [125]:
x=1
y=3
z=x+y
print(z) #para dar resultado
print("x=",x)

4
x= 1


##Tipo de datos integrados

Tipo    | Descripción
--------|-------------
String  | Cadena de texto
int     | Número entero
float   | Numero real
bool    | booleano                     #son True o False

## **Variables**
Símbolo que nos permite obtener información referente al lugar de almacenamiento de un dato en memoria

In [126]:
nom = "Johseline"
apell = 'Chuquimallco'
print(len(nom)) #cuenta el número de letras
print(len(apell))

9
12


In [127]:
print(nom)
print(apell)

Johseline
Chuquimallco


In [128]:
type(nom) #Tipo de dato

str

## **Operadores ariméticos y operadores lógicos**

Descripción  | Operador
-------------|-------------
Suma         | +
Diferencia   | -
Producto     | *
División     | /
Potencia     | **
Módulo       | %
Disyunción   | or
Conjunción   | and
Negación     | not

##Ejemplos de operadores aritméticos y operadores lógicos

In [129]:
a=5**2+80/2
print(a)

65.0


In [130]:
temperatura = 25 # Pero si ponemos mayor a 30, no ejecuta
llueve = False
# Se ejecuta si no hace calor (temperatura es 30 o más) Y no llueve
if not (temperatura >= 30 and not llueve):
  print("No es un día de mucho calor y tampoco llueve.")


No es un día de mucho calor y tampoco llueve.




```
# Esto tiene formato de código
```

## **Inserción de código LaTex**

$\frac{a}{b+c}$


$\int_{\varOmega}\frac{\partial f}{\partial x_{i}}dx$

## **Funciones matemáticas del módulo math**

## **Funciones integradas**

Podemos ver tipos y funciones integradas
[Enlace](https://docs.python.org/es/3/library/stdtypes.html#list)


In [131]:
import math #carga el módulo de funciones math

In [132]:
math.gcd(15,36)  #gcd máximo común divisor

3

In [133]:
math.lcm(4, 10, 15) #lcm mínimo común múltiplo

60

In [134]:
math.exp(1) #función exponencial base e  (f(x)=e^1)

2.718281828459045

##Estructura de datos en Python**


Recuperado de [enlace](https://towardsdatascience.com/which-python-data-structure-should-you-use-fa1edd82946c)
<img src="https://miro.medium.com/max/1400/1*2JFd94q0vzsEcr-LB-220g.png">


## **Lista**

In [135]:
lista1=[1, "Jorge",True]
print(type(lista1)) #imprime el tipo de dato asignado a esa variable
print(lista1[0])
print(lista1[1])
print(lista1[2])

<class 'list'>
1
Jorge
True


In [136]:
lista1=[255, "Pedro",lista1]
print(type(lista1)) #imprime el tipo de dato asignado a esa variable
print(lista1[0])
print(lista1[2])
print(lista1[2][2]) #accediendo al elemento con índice 2 del elemento con índice 2 de lista 2

<class 'list'>
255
[1, 'Jorge', True]
True


## **Método y funciones para listas**

In [137]:
edades=[20,25,4,17,25,25]
#edades.sort
edades.sort() #método sort _lo ordena de menor a mayor
edades.sort(reverse=True) #imprimir número en reversa=False entonces bota de menor a mayor, pero si pongo reverse=True entonces bota de mayor a menor
print(edades)
edades.append(100) #agregar un dato
edades.sort()
print(edades)

[25, 25, 25, 20, 17, 4]
[4, 17, 20, 25, 25, 25, 100]


In [138]:
edades.count(25) #número de veces que se repite un número

3

In [139]:
edades.count(1)

0

In [140]:
edades2=[20,25,4,17,25,25]
edades3=sorted(edades2,reverse=True)
print(edades2)
print(edades3)

[20, 25, 4, 17, 25, 25]
[25, 25, 25, 20, 17, 4]


In [141]:
poligonos=["triángulo","cuadrado","trapecio"]
print(poligonos)
poligonos.append("rombo")
print(poligonos)
poligonos.reverse()
print(poligonos)

['triángulo', 'cuadrado', 'trapecio']
['triángulo', 'cuadrado', 'trapecio', 'rombo']
['rombo', 'trapecio', 'cuadrado', 'triángulo']


In [142]:
otros=["hexagono","pentagono"]
poligonos.append(otros)
print(poligonos)
poligonos.insert(0,"rectángulo") #agrega a la lista de poligonos en el índice 0 la palabra "rectangulo" las veces que haga correr
print(poligonos)

['rombo', 'trapecio', 'cuadrado', 'triángulo', ['hexagono', 'pentagono']]
['rectángulo', 'rombo', 'trapecio', 'cuadrado', 'triángulo', ['hexagono', 'pentagono']]


In [143]:
poligonos.remove("cuadrado")
print(poligonos)

['rectángulo', 'rombo', 'trapecio', 'triángulo', ['hexagono', 'pentagono']]


In [144]:
len(poligonos) #cuántos elementos tiene la entrada de poligonos

5

In [145]:
lista3=["a","b","c"]
lista4=["c","d"]
concat1=lista3 + lista4
print(concat1)
concat2=lista4 + lista3
print(concat2)

['a', 'b', 'c', 'c', 'd']
['c', 'd', 'a', 'b', 'c']


## **Tupla**
Estructura similar a la estructura lista, sin embargo es inmutable.
[referencia](https://docs.python.org/es/3/library/stdtypes.html#tuple)

In [146]:
tup=("a","b","c","b")
print(type(tup))
print(tup[0]) #muestra el elemento del índice 0
print(tup.index("c")) #especifica el primer índice dónde está el elemento que queremos
print("Esto",tup,"es una tupla\n")

<class 'tuple'>
a
2
Esto ('a', 'b', 'c', 'b') es una tupla



In [147]:
tup.index("b") #especifica el primer índice dónde está el elemento que queremos

1

## **Rango**
Estructura para almacenar sucesiones finitas de números enteros. Es inmutable!.
[Referencia](https://docs.python.org/es/3/library/stdtypes.html#tuple)

In [148]:
sucesion = range(7)
print(type(sucesion))
print(sucesion)
print(sucesion[0])
print(sucesion[1])
print(sucesion[2])
print(sucesion[3])
print(sucesion[4])
len(sucesion)

print("El objeto sucesion tiene",len(sucesion),"elementos")

<class 'range'>
range(0, 7)
0
1
2
3
4
El objeto sucesion tiene 7 elementos


In [149]:
rango = range(3,7) #aquí es cerrado en 3 y abierto en 7
print(rango)
print(rango[0])
print(rango[3]) #el elemento de índice 3, sería el 6
print(rango.stop) #el útimo elemento de la lista +1, osea sería 6+1=7


range(3, 7)
3
6
7


In [150]:
rango = range(3,7,2) #la razón es la última entrada, osea la razón es 2. Osea estarían 3,5
print(rango)
print(rango[0])
print(rango[1]) #el elemento de índice 1,
print(rango.stop) #el útimo elemento de la lista +1, osea sería 6+1=7

range(3, 7, 2)
3
5
7


## **Funciones integradas**

In [151]:
x = -3.1415
y = abs(x**2) # función valor absoluto
print(y)

9.86902225


In [152]:
x = 2
y = 3
z = pow(x,y) # función potencia
print(z)

8


In [153]:
m=max(x,y) # función máximo
print(m)

3


## **Array**

Estructura que almacena datos del mismo tipo. Es mutable. [referencia](https://docs.python.org/es/3/library/array.html?highlight=array#module-array)

In [154]:
from array import array
a = array('l',[-1, 3, -3, -4, 5]) #ntero con signo #array, todos los datos tienen que ser del mismo tipo
print("longitud de a: ",len(a))
print(a[0])
print(a[1])
print(a[2])
print(a[3])
print(a[4])
suma = a[0]+a[4]
print(suma)


longitud de a:  5
-1
3
-3
-4
5
4


In [155]:
import array as arr
numbers = arr.array('i',[10,20,30])
type(numbers)

array.array

## Conjunto (set)
Estructura de datos con almacenamiento y operaciones similar al de los conjuntos matemáticos.
[Referencia](https://www.w3schools.com/python/python_sets.asp)

In [156]:
A1 = {"rojo", "verde", "azul"}
A2 = {"verde", "negro", "amarillo"}
print(type(A1))
print(A1)

<class 'set'>
{'rojo', 'verde', 'azul'}


In [157]:
A3 = A1.intersection(A2) #intersección
print(type(A3))
print(A3)
A4 = A1.difference(A2) #diferencia
print(A4)
A5=A1.union(A2)
print(A5)

<class 'set'>
{'verde'}
{'rojo', 'azul'}
{'rojo', 'amarillo', 'azul', 'negro', 'verde'}


In [158]:
A6=A1.isdisjoint(A2) #disjunción (osea hay o no intersección)
print(A6)
A7=A1.__contains__("ab") #¿está contenido?
print(A7)

False
False


In [159]:
c=set(range(4,7))
print(type(c))
print(c)

<class 'set'>
{4, 5, 6}


In [160]:
d=set([range(4,7),"hola",13])
print(type(d))
print(d)

<class 'set'>
{13, range(4, 7), 'hola'}


In [161]:
D={"Jorge","Pedro","Juan","Hector"} #para eliminar según orden de python
D.pop()
print(D)
D.remove("Pedro") #   para eliminar uno específico
print(D)
D.add(24) #para añadir
print(D)

{'Jorge', 'Hector', 'Juan'}


KeyError: 'Pedro'

In [ ]:
D={"Jorge","Pedro","Juan","Hector"}
for i in D: #i=iterador osea recorre las entradas uno por uno
    print(i)


Pedro
Jorge
Hector
Juan


# Librería numpy
Da soporte para crear vectores y matrices multidimensionales grandes, contiene una gran colección de funciones matemáticas de alto nivel para operar con ellas.

<img src="https://aprendeconalf.es/docencia/python/manual/img/numpy-logo.png">

## Clase ndarray
Contiene las estructuras de datos para almacenar las arreglos multidimensionales de datos homogéneos (todos los elementos de una matriz que tienen el mismo tipo de dato).
[Referencia](https://numpy.org/doc/stable/reference/generated/numpy.array.html)

In [ ]:
import numpy as np
mat1 = np.array([1,2,3])
print(type(mat1)) #tipo de dato 
print(mat1)
print(mat1.dtype) #tipo de dato con rango más alt(más amplio)

<class 'numpy.ndarray'>
[1 2 3]
int64


In [ ]:
mat2 = np.array([[1,2,3],[4,5,6]]) #fila,columna
print(mat2)
print(mat2.shape) #nro de (2 filas, 3 columnas)
print(mat2.nbytes) #cuánto bytes utiliza en la memoria
print(mat2.max()) #entrada con mayor valor

[[1 2 3]
 [4 5 6]]
(2, 3)
48
6


In [ ]:
mat2 = np.array([[1,2,3],[4,5,6]])
print(mat2)
print(mat2.shape)
print(mat2.nbytes)
print(mat2.max())

[[1 2 3]
 [4 5 6]]
(2, 3)
48
6


## Acceso a la matriz

In [ ]:
(mat2[0,0]+mat2[0,2])*mat2[1,1] # operación con algunas entradas de la matriz mat2

np.int64(20)

In [ ]:
matriz=np.array([[1.,2.,3.],[5.,6.,7.],[8.,9.,10.]])
print(matriz)
print(mat1.dtype)
matriz.trace()


[[ 1.  2.  3.]
 [ 5.  6.  7.]
 [ 8.  9. 10.]]
int64


np.float64(17.0)

In [ ]:
matriz[0,0]+matriz[1,1]+matriz[2,2] #traza manualmente

np.float64(17.0)

In [ ]:
np.linalg.det(matriz) #para hallar la deterinante

np.float64(0.0)

##**Ejemplos adicionales**

In [177]:
matriz1=np.array([[18,20,30],[50,60,75],[85,92,48]])
matriz5=np.array([[8,22,38],[68,14,28],[5,2,8]])
print(matriz1)
print(matriz5)
print(mat1.dtype)

[[18 20 30]
 [50 60 75]
 [85 92 48]]
[[ 8 22 38]
 [68 14 28]
 [ 5  2  8]]
int64


In [175]:
suma=matriz1+matriz5
print(suma)

[[ 26  42  68]
 [118  74 103]
 [ 90  94  56]]


##**Diferentes maneras de hallar el producto de matrices**

In [199]:
producto=matriz1*matriz5
print(producto)
producto2=np.dot(matriz1,matriz5)
producto3=np.matmul(matriz1,matriz5)
producto4=matriz1 @ matriz5
print(" \n producto2=\n ",producto2,"\n \n producto3= \n", producto3," \n \n producto4= \n", producto4)
print(matriz1.dot(matriz5))

[[ 144  440 1140]
 [3400  840 2100]
 [ 425  184  384]]
 
 producto2=
  [[1654  736 1484]
 [4855 2090 4180]
 [7176 3254 6190]] 
 
 producto3= 
 [[1654  736 1484]
 [4855 2090 4180]
 [7176 3254 6190]]  
 
 producto4= 
 [[1654  736 1484]
 [4855 2090 4180]
 [7176 3254 6190]]
[[1654  736 1484]
 [4855 2090 4180]
 [7176 3254 6190]]


In [ ]:
np.linalg.inv(matriz1) #para sacar la inversa de una matriz

array([[ 0.51145038, -0.22900763,  0.03816794],
       [-0.50572519,  0.21450382, -0.01908397],
       [ 0.06361323, -0.00559796, -0.01017812]])

In [ ]:
matriz2=np.array([[1.,2.,3.],[5.,6.,7.],[8.,9.,10.]])
matriz3=np.array([[0.,0.,3.],[5.,6.,0.],[8.,0.,0.]])
print(type(matriz2))
print(matriz2.dtype)
matriz4=np.array(([[1.,2.,3.],[5.,6.,7.],[8.,9.,10.]]), dtype=np.float64)
mat2T=matriz2.T
print(mat2T)


<class 'numpy.ndarray'>
float64
[[ 1.  5.  8.]
 [ 2.  6.  9.]
 [ 3.  7. 10.]]


In [182]:
traza=matriz2.trace() #método de traza 
traza2=matriz[0,0]+matriz[1,1]+matriz[2,2]
traza3=np.trace(matriz2) #función de numpy que calcula también traza
print("traza =",traza,"traza2 =",traza2,"traza3 =",traza3)

traza = 17.0 traza2 = 17.0 traza3 = 17.0


In [ ]:
mat=np.zeros((2,3), dtype=np.int32) #matriz de ceros 2 filas * 3 columnas
print(mat)

[[0 0 0]
 [0 0 0]]


In [ ]:
vect=np.arange(2,6,0.5) #(empieza en 2, va hasta 6 o antes, de cuánto en cuanto van)
print(vect)

[2.  2.5 3.  3.5 4.  4.5 5.  5.5]


In [209]:
vect2=np.linspace(2,6,7)
print(vect2)

[2.         2.66666667 3.33333333 4.         4.66666667 5.33333333
 6.        ]


In [ ]:
mat2=np.random.rand(3,3) #construye una matriz de ceros
print(mat2)

[[2.01255607e-01 6.13103685e-01 2.20123499e-04]
 [8.73055893e-01 3.65272735e-01 7.11315646e-01]
 [5.95970214e-02 9.41553321e-01 5.78819097e-01]]


In [ ]:
mat3=np.empty((3,3),dtype=np.float32) #constructor de una matriz vacia, osea que está separando un espacio de memoria. Y los datos que aparecen y no son ceros son datos basura osea que se imprimen pero no se van a usar, ellos están en la memoria sobrando.
print(mat3)

[[0.0000000e+00 0.0000000e+00 1.2926615e+17]
 [7.0205053e-43 1.2926134e+17 7.0205053e-43]
 [1.2926477e+17 7.0205053e-43 0.0000000e+00]]


In [ ]:
mat3[0,0]=np.pi # ingresamos un número en una posición específica
print(mat3)

[[3.1415927e+00 0.0000000e+00 1.2926615e+17]
 [7.0205053e-43 1.2926134e+17 7.0205053e-43]
 [1.2926477e+17 7.0205053e-43 0.0000000e+00]]


In [219]:
mat3[0,0]=8
print(mat3)

[[8.0000000e+00 0.0000000e+00 1.2926615e+17]
 [7.0205053e-43 1.2926134e+17 7.0205053e-43]
 [1.2926477e+17 7.0205053e-43 0.0000000e+00]]
