In [1]:
import numpy as np

In [12]:
A=np.random.rand(6,5)
print(A)

#print(A[0:2,0:2]) #para obtener fila 1 y 2

print("\n",A[2:4,:])

#print("\n",A[4:2,:])

[[0.03176393 0.92595696 0.94695798 0.85575875 0.13248181]
 [0.82007344 0.00658258 0.09869122 0.428024   0.03616373]
 [0.70764257 0.21032537 0.11757383 0.06809864 0.33734682]
 [0.86597816 0.1798806  0.30364076 0.81420111 0.90160704]
 [0.88615656 0.99751194 0.87134239 0.32172861 0.7027952 ]
 [0.62664077 0.35120144 0.82977692 0.11118608 0.21563742]]

 [[0.70764257 0.21032537 0.11757383 0.06809864 0.33734682]
 [0.86597816 0.1798806  0.30364076 0.81420111 0.90160704]]
